set_property PACKAGE_PIN E3 [get_ports clk_100mhz_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz_i]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_100mhz_i]
set_property PACKAGE_PIN N17 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property PACKAGE_PIN T8 [get_ports intr_i]
set_property IOSTANDARD LVCMOS33 [get_ports intr_i]
set_property PACKAGE_PIN D4 [get_ports tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_o]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_false_path -from [get_ports rst_i]
set_false_path -from [get_ports intr_i]
set_property PACKAGE_PIN H17 [get_ports {led_o[0]}]
set_property PACKAGE_PIN K15 [get_ports {led_o[1]}]
set_property PACKAGE_PIN J13 [get_ports {led_o[2]}]
set_property PACKAGE_PIN N14 [get_ports {led_o[3]}]
set_property PACKAGE_PIN R18 [get_ports {led_o[4]}]
set_property PACKAGE_PIN V17 [get_ports {led_o[5]}]
set_property PACKAGE_PIN U17 [get_ports {led_o[6]}]
set_property PACKAGE_PIN U16 [get_ports {led_o[7]}]
set_property PACKAGE_PIN V16 [get_ports {led_o[8]}]
set_property PACKAGE_PIN T15 [get_ports {led_o[9]}]
set_property PACKAGE_PIN U14 [get_ports {led_o[10]}]
set_property PACKAGE_PIN T16 [get_ports {led_o[11]}]
set_property PACKAGE_PIN V15 [get_ports {led_o[12]}]
set_property PACKAGE_PIN V14 [get_ports {led_o[13]}]
set_property PACKAGE_PIN V12 [get_ports {led_o[14]}]
set_property PACKAGE_PIN V11 [get_ports {led_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[*]}]
set_false_path -from [get_ports rst_i] -to [all_registers]

